# site settings
title: Media Portrayals of Minorities Project
subtitle: 
email: ebleich@middlebury.edu
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
# baseurl: "erik-bleich.github.io/" # the subpath of your site, e.g. /blog
url: "https://erik-bleich.github.io/" # the base hostname & protocol for your site
author:
street_address:  Department of Political Science <br /> Middlebury College
city: Middlebury
state: VT
zip_code: "05753"
country: United States of America
phone: (802) 443-3254

# social settings
500px_url:
facebook_url:
github_url: https://github.com/erik-bleich
gitlab_url: https://gitlab.com/u/erik-bleich

# include: ["_pages"]
permalink: /:title/

# build settings
markdown: kramdown

sass:
  style: compressed
