# site settings
title: Media and Minorities
subtitle: by MMOMP Lab
email: test@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
# baseurl: "erik-bleich.github.io/" # the subpath of your site, e.g. /blog
url: "https://erik-bleich.github.io/" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://github.com/erik-bleich
gitlab_url: https://gitlab.com/u/erik-bleich
googleplus_url:
instagram_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
